site_name: Legal documents
site_url: https://investigativedata.io/legal
repo_url: https://github.com/investigativedata/legal
nav:
  - english:
    - TOS: en/tos.md
    - SLA Managed OpenAleph: en/sla-openaleph.md
    - SLA Managed SSO: en/sla-sso.md
    - DPA: en/dpa.md
    - TOMS: en/toms.md
    - Subprocessors: en/subprocessors.md
    - NDA: en/nda.md
    - Data privacy (website): en/dataprivacy-io.md
  - deutsch:
    - AGB: de/agb.md
    - SLA Managed OpenAleph: de/sla-openaleph.md
    - SLA Managed SSO: de/sla-sso.md
    - AVV: de/avv.md
    - TOMS: de/toms.md
    - Unterauftragnehmer: de/unterauftragnehmer.md
    - NDA: de/nda.md
    - Datenschutz (website): de/datenschutzerklaerung-io.md
  - Contact:
    - › Email us: mailto:legal@investigativedata.org
    - › investigativedata.io: https://investigativedata.io
theme:
  name: material
  custom_dir: overrides
  logo: https://cdn.investigativedata.org/style/logo_basic_dark.svg
  favicon: https://cdn.investigativedata.org/style/favicon.svg
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.sections
    # - navigation.footer
    - toc.follow
extra_css:
  - stylesheets/extra.css
markdown_extensions:
  - attr_list
extra:
  social:
    - icon: material/web
      link: https://investigativedata.io
    - icon: material/mail
      link: mailto:legal@investigativedata.org
    - icon: material/github
      link: https://github.com/investigativedata
    - icon: material/linkedin
      link: https://www.linkedin.com/company/investigativedata/
